### PR TITLE
some old & new suggestions...

### PR DESCRIPTION
**Pull request by grosged**
I re-read the old ones ;)

### CODE REVIEW

**Comment by TheMachine02** [comment]
Je suis ok pour la plupart, juste l'optimisation estimant que atomic_rw.lock_write retourne a=0 me semble hasardeuse au cas où cette valeur change... Si tu pouvais juste revert ça, comme ça je merge :)

**Review by TheMachine02 — CHANGES_REQUESTED** [review]
In case atomic_rw.lock_write change, assumption that register a is null at exit of this function may break. As assertion will be hard to enforce, reverting this optimization seems the safer path.

**Comment by grosged** [comment]
Ah ok, I understand the "risky trick" . I'm gonna revert this part ;)

**Comment by grosged** [comment]
I've made another Pull Request in order to go back

**Pull request merged**
